# Generated by Django 3.2.25 on 2025-10-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20251008_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls')], max_length=10)),
                ('warden_name', models.CharField(max_length=200)),
                ('warden_contact', models.CharField(max_length=15)),
                ('total_rooms', models.IntegerField()),
                ('occupied_rooms', models.IntegerField(default=0)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('publisher', models.CharField(max_length=200)),
                ('published_year', models.IntegerField()),
                ('category', models.CharField(choices=[('textbook', 'Text Book'), ('reference', 'Reference Book'), ('journal', 'Journal'), ('magazine', 'Magazine'), ('ebook', 'E-Book')], max_length=20)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('shelf_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/covers/')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_books', to='main_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit Based'), ('need', 'Need Based'), ('sports', 'Sports'), ('minority', 'Minority'), ('govt', 'Government'), ('private', 'Private')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_recipients', models.IntegerField()),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_contact', models.CharField(max_length=15)),
                ('route_details', models.TextField(help_text='Stops and timings')),
                ('fee_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_seats', models.IntegerField(default=40)),
                ('occupied_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='annual_family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='caste_category',
            field=models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/caste/'),
        ),
        migrations.AddField(
            model_name='student',
            name='character_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/character/'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_type',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('phd', 'Ph.D')], default='btech', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1, help_text='Current semester number'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/diploma/'),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='diploma_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/disability/'),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_category_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_name',
            field=models.CharField(blank=True, help_text='E.g., JEE Main, EAMCET, GATE', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/income/'),
        ),
        migrations.AddField(
            model_name='student',
            name='income_certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/migration/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='student_signatures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('dropped', 'Dropped Out'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_board',
            field=models.CharField(blank=True, max_length=100, verbose_name='10th Board'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/10th/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marks_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='10th School Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='10th Passing Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/tc/'),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_board',
            field=models.CharField(blank=True, max_length=100, verbose_name='12th Board'),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/12th/'),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_marks_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='12th School Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='12th Passing Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course', verbose_name='Program/Branch'),
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')])),
                ('total_credits', models.IntegerField(default=0)),
                ('credits_earned', models.IntegerField(default=0)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='SGPA')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='CGPA')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_backlogs', models.BooleanField(default=False)),
                ('number_of_backlogs', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='main_app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='main_app.student')),
            ],
            options={
                'ordering': ['student', 'semester'],
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Why you deserve this scholarship')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='scholarship_docs/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='applied', max_length=20)),
                ('review_remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scholarships', to='main_app.staff')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='main_app.student')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LibraryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='issued', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='main_app.library')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_issues', to='main_app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_issues', to='main_app.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('allocated_date', models.DateField(auto_now_add=True)),
                ('rent_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='main_app.hostel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocation', to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('diploma', 'Diploma'), ('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('phd', 'Ph.D')], max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')])),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('development_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='main_app.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='main_app.session')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'unique_together': {('course', 'course_type', 'semester', 'session')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('online', 'Online/UPI'), ('card', 'Credit/Debit Card')], default='online', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main_app.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='main_app.student')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=200)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_allocation', to='main_app.student')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='main_app.transport')),
            ],
            options={
                'unique_together': {('student', 'transport')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('external_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('O', 'O (Outstanding)'), ('A+', 'A+ (Excellent)'), ('A', 'A (Very Good)'), ('B+', 'B+ (Good)'), ('B', 'B (Above Average)'), ('C', 'C (Average)'), ('P', 'P (Pass)'), ('F', 'F (Fail)'), ('AB', 'AB (Absent)')], max_length=5)),
                ('credits', models.IntegerField(default=3)),
                ('is_pass', models.BooleanField(default=True)),
                ('semester_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='main_app.semesterresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='main_app.subject')),
            ],
            options={
                'unique_together': {('semester_result', 'subject')},
            },
        ),
    ]
