# Generated by Django 3.2.25 on 2025-10-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_activityparticipation_alumni_antiraggingcommittee_certificate_disciplinaryaction_gatepass_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=200)),
                ('room_type', models.CharField(choices=[('classroom', 'Regular Classroom'), ('lab', 'Laboratory'), ('seminar', 'Seminar Hall'), ('auditorium', 'Auditorium'), ('library', 'Library Reading Room'), ('staff_room', 'Staff Room'), ('tutorial', 'Tutorial Room')], default='classroom', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(help_text='Maximum number of students')),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_audio_system', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_computers', models.BooleanField(default=False)),
                ('computer_count', models.IntegerField(default=0, help_text='Number of computers (for labs)')),
                ('is_available', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='main_app.department')),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('electrical', 'Electrical'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('equipment', 'Equipment'), ('structural', 'Structural'), ('other', 'Other')], max_length=20)),
                ('issue_description', models.TextField()),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending_parts', 'Pending Parts')], default='reported', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Maintenance staff assigned', max_length=200)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='main_app.classroom')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('class', 'Regular Class'), ('exam', 'Examination'), ('event', 'Event/Seminar'), ('meeting', 'Meeting'), ('workshop', 'Workshop'), ('other', 'Other')], max_length=20)),
                ('purpose', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_attendees', models.IntegerField(help_text='Number of expected participants')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special setup needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to='main_app.staff')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_bookings', to='main_app.staff')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main_app.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.subject')),
            ],
            options={
                'ordering': ['-booking_date', 'start_time'],
            },
        ),
    ]
