# Generated by Django 5.2.7 on 2025-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_customuser_username_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
    ]
