# Generated by Django 5.2.7 on 2025-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, help_text='Academic and extracurricular achievements'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_fee_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_mode',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Merit', 'Merit'), ('Management', 'Management'), ('NRI', 'NRI'), ('Sports', 'Sports'), ('Cultural', 'Cultural')], default='Merit', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_quota',
            field=models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS'), ('PH', 'PH'), ('NRI', 'NRI')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to='documents/affidavit/'),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank_passbook/'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth/'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='domicile_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/domicile/'),
        ),
        migrations.AddField(
            model_name='student',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/driving_license/'),
        ),
        migrations.AddField(
            model_name='student',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='english_proficiency',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam_scorecard',
            field=models.FileField(blank=True, null=True, upload_to='documents/entrance/'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gap_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/gap/'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_known',
            field=models.TextField(blank=True, help_text='Languages known (comma-separated)'),
        ),
        migrations.AddField(
            model_name='student',
            name='library_card_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/medical/'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions or allergies'),
        ),
        migrations.AddField(
            model_name='student',
            name='migration_certificate_from_board',
            field=models.FileField(blank=True, null=True, upload_to='documents/migration_board/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='student',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='documents/passport/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='provisional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/provisional/'),
        ),
        migrations.AddField(
            model_name='student',
            name='sports_played',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/undertaking/'),
        ),
        migrations.AddField(
            model_name='student',
            name='voter_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/voter_id/'),
        ),
        migrations.AddField(
            model_name='student',
            name='voter_id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='work_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
