# Generated by Django 5.2.7 on 2025-10-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_student_aadhaar_card_student_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='affidavit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='student',
            name='domicile_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='student',
            name='driving_license_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='english_proficiency',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gap_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='github_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='languages_known',
        ),
        migrations.RemoveField(
            model_name='student',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medical_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='migration_certificate_from_board',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio_website',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_designation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_employer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='provisional_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports_played',
        ),
        migrations.RemoveField(
            model_name='student',
            name='undertaking_form',
        ),
        migrations.RemoveField(
            model_name='student',
            name='voter_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='voter_id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_experience_years',
        ),
    ]
