# Generated by Django 5.2.7 on 2025-10-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_student_affidavit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='diploma_branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma_college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_board',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_marks_total',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_year',
        ),
    ]
