# Generated by Django 5.2.7 on 2025-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_student_diploma_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('subject', 'date', 'session')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='attendance_subject_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session', 'date'], name='attendance_session_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['created_at'], name='attendance_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type'], name='exam_type_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['session', 'semester'], name='exam_session_semester_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date'], name='exam_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['end_date'], name='exam_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='exam_published_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_at'], name='exam_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='fee_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student', 'payment_date'], name='fee_payment_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['status'], name='fee_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_number'], name='fee_payment_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['created_at'], name='fee_payment_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['employee_id'], name='staff_employee_id_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department'], name='staff_department_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['designation'], name='staff_designation_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['mobile_number'], name='staff_mobile_number_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['aadhaar_number'], name='staff_aadhaar_number_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['date_of_joining'], name='staff_joining_date_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='student_roll_number_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='student_admission_number_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'session'], name='student_course_session_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_year'], name='student_admission_year_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_semester'], name='student_current_semester_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mobile_number'], name='student_mobile_number_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['aadhaar_number'], name='student_aadhaar_number_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_status'], name='student_status_idx'),
        ),
    ]
