# Generated by Django 5.2.7 on 2025-10-12 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_app', '0014_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('payment', 'Payment'), ('grade_change', 'Grade Change'), ('attendance_override', 'Attendance Override'), ('fee_waiver', 'Fee Waiver'), ('scholarship_approval', 'Scholarship Approval'), ('disciplinary_action', 'Disciplinary Action'), ('system_config', 'System Configuration')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values for updates', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values for creates/updates', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data', null=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_log_time_idx'), models.Index(fields=['user', 'timestamp'], name='audit_log_user_time_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_log_action_time_idx'), models.Index(fields=['severity', 'timestamp'], name='audit_log_severity_time_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_log_ip_time_idx'), models.Index(fields=['success', 'timestamp'], name='audit_log_success_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('export', 'Export'), ('print', 'Print'), ('download', 'Download'), ('bulk_access', 'Bulk Access')], max_length=20)),
                ('data_type', models.CharField(choices=[('student_personal', 'Student Personal Data'), ('staff_personal', 'Staff Personal Data'), ('financial', 'Financial Data'), ('academic_records', 'Academic Records'), ('attendance_data', 'Attendance Data'), ('exam_results', 'Exam Results'), ('fee_records', 'Fee Records'), ('library_records', 'Library Records'), ('placement_data', 'Placement Data'), ('medical_records', 'Medical Records'), ('disciplinary_records', 'Disciplinary Records')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=1, help_text='Number of records accessed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(blank=True, help_text='Reason for access')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Access Log',
                'verbose_name_plural': 'Data Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='data_access_time_idx'), models.Index(fields=['user', 'timestamp'], name='data_access_user_time_idx'), models.Index(fields=['data_type', 'timestamp'], name='data_access_data_type_idx'), models.Index(fields=['access_type', 'timestamp'], name='data_access_access_type_idx'), models.Index(fields=['ip_address', 'timestamp'], name='data_access_ip_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('suspicious_request', 'Suspicious Request'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('data_breach_attempt', 'Data Breach Attempt'), ('sql_injection_attempt', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('file_upload_attempt', 'Malicious File Upload'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('concurrent_session_limit', 'Concurrent Session Limit'), ('admin_access_denied', 'Admin Access Denied'), ('bulk_data_access', 'Bulk Data Access'), ('export_large_dataset', 'Large Dataset Export'), ('permission_escalation', 'Permission Escalation Attempt'), ('session_hijack_attempt', 'Session Hijack Attempt')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField()),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sec_event_time_idx'), models.Index(fields=['event_type', 'timestamp'], name='sec_event_type_time_idx'), models.Index(fields=['severity', 'timestamp'], name='sec_event_sev_time_idx'), models.Index(fields=['ip_address', 'timestamp'], name='sec_event_ip_time_idx'), models.Index(fields=['is_resolved', 'timestamp'], name='sec_event_res_time_idx')],
            },
        ),
    ]
