# Generated by Django 5.2.7 on 2025-10-13 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_admissionapplication_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='A9A0F4361665', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=200)),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude Test'), ('technical', 'Technical Round'), ('coding', 'Coding Round'), ('group_discussion', 'Group Discussion'), ('hr', 'HR Round'), ('managerial', 'Managerial Round'), ('final', 'Final Round')], max_length=30)),
                ('round_number', models.IntegerField(default=1)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='offline', max_length=20)),
                ('venue', models.CharField(blank=True, help_text='Physical venue or meeting link', max_length=300)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration per candidate in minutes')),
                ('instructions', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='main_app.placementdrive')),
            ],
            options={
                'ordering': ['placement_drive', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='main_app.placementapplication')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main_app.interviewround')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='main_app.student')),
            ],
            options={
                'ordering': ['interview_round', 'slot_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=200)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254)),
                ('technical_skills', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('communication_skills', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('problem_solving', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('attitude', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('overall_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('recommendation', models.CharField(choices=[('strongly_reject', 'Strongly Reject'), ('reject', 'Reject'), ('maybe', 'Maybe'), ('recommend', 'Recommend'), ('strongly_recommend', 'Strongly Recommend')], max_length=30)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='main_app.student')),
                ('interview_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main_app.interviewslot')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_type', models.CharField(choices=[('faculty', 'Faculty Coordinator'), ('student', 'Student Coordinator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='placement_coordinators', to='main_app.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_coordinators', to='main_app.session')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_coordinator', to='main_app.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_coordinator', to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('purpose', models.TextField(help_text='Purpose of visit (PPT, Interview, etc.)')),
                ('attendees_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main_app.company')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_visits', to='main_app.session')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_visits', to='main_app.placementcoordinator')),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='PlacementOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('part_time', 'Part Time')], default='full_time', max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('ctc', models.DecimalField(decimal_places=2, help_text='Cost to Company in LPA', max_digits=10)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='For internships', max_digits=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, upload_to='placement/offer_letters/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main_app.placementapplication')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main_app.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_offers', to='main_app.student')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diploma_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('technical_skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('programming_languages', models.TextField(blank=True, help_text='Comma-separated languages')),
                ('certifications', models.TextField(blank=True)),
                ('internship_experience', models.TextField(blank=True)),
                ('project_experience', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='placement/student_resumes/')),
                ('resume_updated_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_job_locations', models.TextField(blank=True, help_text='Comma-separated locations')),
                ('preferred_job_roles', models.TextField(blank=True, help_text='Comma-separated roles')),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_placed', models.BooleanField(default=False)),
                ('placement_date', models.DateField(blank=True, null=True)),
                ('is_active_for_placement', models.BooleanField(default=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placed_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_students', to='main_app.company')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to='main_app.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['placement_drive', 'scheduled_date'], name='main_app_in_placeme_81e8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['scheduled_date', 'is_completed'], name='main_app_in_schedul_dc1b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['interview_round', 'status'], name='main_app_in_intervi_db7d89_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['student', 'status'], name='main_app_in_student_5b3c15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewslot',
            unique_together={('interview_round', 'slot_time')},
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['student', 'overall_rating'], name='main_app_in_student_4f7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['interview_slot'], name='main_app_in_intervi_aeb55e_idx'),
        ),
        migrations.AddIndex(
            model_name='placementcoordinator',
            index=models.Index(fields=['coordinator_type', 'is_active'], name='main_app_pl_coordin_ec6755_idx'),
        ),
        migrations.AddIndex(
            model_name='placementcoordinator',
            index=models.Index(fields=['session', 'is_active'], name='main_app_pl_session_64a586_idx'),
        ),
        migrations.AddIndex(
            model_name='companyvisit',
            index=models.Index(fields=['company', 'visit_date'], name='main_app_co_company_15dd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='companyvisit',
            index=models.Index(fields=['status', 'visit_date'], name='main_app_co_status_0fc802_idx'),
        ),
        migrations.AddIndex(
            model_name='placementoffer',
            index=models.Index(fields=['student', 'status'], name='main_app_pl_student_b52c35_idx'),
        ),
        migrations.AddIndex(
            model_name='placementoffer',
            index=models.Index(fields=['company', 'offer_type'], name='main_app_pl_company_35b052_idx'),
        ),
        migrations.AddIndex(
            model_name='placementoffer',
            index=models.Index(fields=['issued_date'], name='main_app_pl_issued__3ee6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacementprofile',
            index=models.Index(fields=['is_placed', 'is_active_for_placement'], name='main_app_st_is_plac_7eb6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacementprofile',
            index=models.Index(fields=['current_cgpa'], name='main_app_st_current_3c11c3_idx'),
        ),
    ]
