# Generated by Django 5.2.7 on 2025-10-13 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_admissionapplication_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], default='multiple_choice', max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='43C72376EDE3', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Content'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('resource', 'Resource'), ('discussion', 'Discussion')], default='text', max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, help_text='Text content or instructions')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lms/modules/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main_app.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_modules', to='main_app.staff')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_modules', to='main_app.coursemodule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main_app.subject')),
            ],
            options={
                'ordering': ['course', 'subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_student_posts', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='main_app.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forums', to='main_app.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='main_app.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.discussionforum')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main_app.discussionpost')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('peer_review', 'Peer Review')], default='individual', max_length=20)),
                ('submission_type', models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Submission'), ('both', 'File and Text')], default='file', max_length=20)),
                ('max_marks', models.IntegerField(default=100)),
                ('word_limit', models.IntegerField(default=0, help_text='Word limit for text submissions')),
                ('file_size_limit', models.IntegerField(default=10, help_text='File size limit in MB')),
                ('allowed_file_types', models.CharField(default='pdf,doc,docx', help_text='Comma-separated file extensions', max_length=200)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('late_submission_allowed', models.BooleanField(default=False)),
                ('late_penalty_percentage', models.FloatField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('allow_resubmission', models.BooleanField(default=False)),
                ('max_resubmissions', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assignments', to='main_app.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lms_assignments', to='main_app.staff')),
                ('resources', models.ManyToManyField(blank=True, related_name='lms_assignments', to='main_app.coursemodule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assignments', to='main_app.subject')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='LMSAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='lms/assignments/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submission_number', models.IntegerField(default=1)),
                ('is_resubmission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main_app.lmsassignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_lms_submissions', to='main_app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assignment_submissions', to='main_app.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main_app.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=0, help_text='Time limit in minutes (0 = no limit)')),
                ('max_attempts', models.IntegerField(default=1)),
                ('passing_score', models.IntegerField(default=60, help_text='Passing percentage')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='main_app.coursemodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken in seconds')),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Student answers in JSON format')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main_app.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='main_app.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('notes', models.TextField(blank=True)),
                ('bookmarked', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='main_app.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_progress', models.FloatField(default=0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time in seconds')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main_app.course')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='main_app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='main_app.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='main_app_co_student_ddf5f0_idx'), models.Index(fields=['course', 'status'], name='main_app_co_course__09a545_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'is_published'], name='main_app_co_course__ebeba6_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['subject', 'module_type'], name='main_app_co_subject_a2a436_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionforum',
            index=models.Index(fields=['course', 'is_active'], name='main_app_di_course__5fc349_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['forum', 'is_approved'], name='main_app_di_forum_i_6dec9e_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['author', 'created_at'], name='main_app_di_author__17b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassignment',
            index=models.Index(fields=['course', 'is_published'], name='main_app_lm_course__fdd460_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassignment',
            index=models.Index(fields=['due_date', 'is_published'], name='main_app_lm_due_dat_4426a5_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='main_app_lm_assignm_f50700_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassignmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='main_app_lm_student_90b06d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmsassignmentsubmission',
            unique_together={('assignment', 'student', 'submission_number')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'available_from'], name='main_app_qu_is_acti_3d9588_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['difficulty'], name='main_app_qu_difficu_f1ccc9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'question_type'], name='main_app_qu_quiz_id_56902e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='main_app_qu_student_ea1c29_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status', 'started_at'], name='main_app_qu_status_5b53a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'quiz', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'is_completed'], name='main_app_st_student_f6c0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['module', 'is_completed'], name='main_app_st_module__3d1c64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'module')},
        ),
    ]
