# Generated by Django 5.2.7 on 2025-10-13 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='8FCF1970B5F0', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the link', max_length=200)),
                ('url', models.URLField(help_text='Full URL including http:// or https://')),
                ('description', models.TextField(blank=True, help_text='Brief description of the link')),
                ('icon', models.CharField(default='fas fa-link', help_text='FontAwesome icon class', max_length=50)),
                ('category', models.CharField(choices=[('academic', 'Academic Resources'), ('administrative', 'Administrative Services'), ('external', 'External Resources'), ('internal', 'Internal Services')], default='external', max_length=20)),
                ('link_type', models.CharField(choices=[('website', 'Website'), ('portal', 'Portal'), ('resource', 'Resource'), ('service', 'Service'), ('course', 'Online Course')], default='website', max_length=20)),
                ('target', models.CharField(choices=[('_blank', 'New Tab'), ('_self', 'Same Tab')], default='_blank', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this link')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured/prominent link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Link',
                'verbose_name_plural': 'Public Links',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
