# Generated by Django 4.2.11 on 2025-10-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_admissionapplication_application_number_and_more'),
    ]

    operations = [
    ]
