# Generated by Django 4.2.11 on 2025-10-26 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20251026_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], unique=True)),
                ('year_name', models.CharField(help_text='e.g., First Year, Second Year', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['year_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
                'ordering': ['-session__start_year', 'academic_year__year_number', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('document_type', models.CharField(choices=[('photo', 'Photo'), ('aadhar', 'Aadhar Card'), ('tenth_cert', '10th Certificate'), ('twelfth_cert', '12th Certificate'), ('transfer_cert', 'Transfer Certificate'), ('migration_cert', 'Migration Certificate'), ('caste_cert', 'Caste Certificate'), ('income_cert', 'Income Certificate'), ('medical_cert', 'Medical Certificate'), ('other', 'Other')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('max_file_size', models.IntegerField(default=5, help_text='Maximum file size in MB')),
                ('allowed_formats', models.CharField(default='pdf,jpg,jpeg,png', help_text='Comma-separated file extensions', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('merit', 'Merit Based'), ('need', 'Need Based'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField()),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], default='email', max_length=10)),
                ('sent_status', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C, D', max_length=10)),
                ('capacity', models.IntegerField(default=60, help_text='Maximum students in this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('10th', '10th Grade Certificate'), ('12th', '12th Grade Certificate'), ('diploma', 'Diploma Certificate'), ('degree', 'Degree Certificate'), ('transfer', 'Transfer Certificate'), ('migration', 'Migration Certificate'), ('conduct', 'Conduct Certificate'), ('bonafide', 'Bonafide Certificate'), ('character', 'Character Certificate'), ('experience', 'Experience Certificate'), ('achievement', 'Achievement Certificate'), ('other', 'Other')], max_length=50)),
                ('certificate_title', models.CharField(max_length=200)),
                ('certificate_file', models.FileField(upload_to='student_certificates/%Y/%m/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/%d/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('verified_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reupload_required', 'Re-upload Required')], default='pending', max_length=20)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Admin remarks for verification')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyvisit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyvisit',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='companyvisit',
            name='session',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='interview_slot',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interviewround',
            name='placement_drive',
        ),
        migrations.AlterUniqueTogether(
            name='interviewslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='application',
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='interview_round',
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereadstatus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereadstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placementcoordinator',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='placementcoordinator',
            name='session',
        ),
        migrations.RemoveField(
            model_name='placementcoordinator',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='placementcoordinator',
            name='student',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='application',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentplacementprofile',
            name='placed_company',
        ),
        migrations.RemoveField(
            model_name='studentplacementprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='typing_in_room',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-bonus_date']},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='loanemi',
            options={'ordering': ['emi_number']},
        ),
        migrations.AlterModelOptions(
            name='payrollstructure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_year']},
        ),
        migrations.AlterModelOptions(
            name='taxdeclaration',
            options={'ordering': ['-financial_year']},
        ),
        migrations.RemoveIndex(
            model_name='attendanceregister',
            name='attendance_reg_emp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceregister',
            name='attendance_reg_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceregister',
            name='attendance_reg_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonus',
            name='bonus_employee_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonus',
            name='bonus_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonus',
            name='bonus_payment_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonus',
            name='bonus_approved_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeesalary',
            name='emp_salary_employee_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeesalary',
            name='emp_salary_eff_from_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeesalary',
            name='emp_salary_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='leave_balance_emp_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='leave_balance_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='loan_employee_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='loan_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='loan_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='loan_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanemi',
            name='loan_emi_loan_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanemi',
            name='loan_emi_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanemi',
            name='loan_emi_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollstructure',
            name='payroll_structure_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollstructure',
            name='payroll_structure_dept_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollstructure',
            name='payroll_structure_eff_from_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollstructure',
            name='payroll_structure_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payslip_emp_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payslip_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslip',
            name='payslip_generated_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxdeclaration',
            name='tax_decl_emp_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxdeclaration',
            name='tax_decl_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxdeclaration',
            name='tax_decl_verified_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendanceregister',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='is_taxable',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='paid_in_salary',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='payment_month',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='payment_year',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='tax_deducted',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='deduct_from_salary',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='first_emi_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_paid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_emi_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='outstanding_interest',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='outstanding_principal',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='principal_paid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='recovery_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='deducted_from_salary',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='emi_date',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='interest_component',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='payslip',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='principal_component',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='loanemi',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='da_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='department',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='esi_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='hra_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='pf_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='research_allowance',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='document_uploaded',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bonus',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Razorpay, PayU, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='remaining_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_emi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanemi',
            name='due_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanemi',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanemi',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanemi',
            name='total_emi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='alternate_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollstructure',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollstructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default=1, help_text='e.g., C23, C24, C25', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main_app.department'),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='main_app.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='tax_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='4D64DC4B90CE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonuses', to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_certificates', to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Management'), (5, 'Parent')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollstructure',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollstructure',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_year',
            field=models.IntegerField(help_text='Ending year (e.g., 2026)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_year',
            field=models.IntegerField(help_text='Starting year (e.g., 2023)'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='financial_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tax_declarations', to='main_app.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceregister',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('staff', 'leave_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('staff', 'month', 'year')},
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='ChatRoomMember',
        ),
        migrations.DeleteModel(
            name='CompanyVisit',
        ),
        migrations.DeleteModel(
            name='InterviewFeedback',
        ),
        migrations.DeleteModel(
            name='InterviewRound',
        ),
        migrations.DeleteModel(
            name='InterviewSlot',
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
        migrations.DeleteModel(
            name='PlacementCoordinator',
        ),
        migrations.DeleteModel(
            name='PlacementOffer',
        ),
        migrations.DeleteModel(
            name='StudentPlacementProfile',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.documenttype'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_certificates', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='feereminder',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.feestructure'),
        ),
        migrations.AddField(
            model_name='feereminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_reminders', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='main_app.feestructure'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific to course (null for all courses)', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='main_app.academicyear'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='main_app.course'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='main_app.department'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='main_app.section'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='main_app.session'),
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='leave_reason',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='da_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='esi_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='hra_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='loan_deduction',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='pf_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='research_allowance',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='accrued',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='annual_quota',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='max_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='used',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='da_amount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='days_absent',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='days_on_leave',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='days_worked',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='esi_amount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='hra_amount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='loan_deduction',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pay_period_month',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pay_period_year',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='payslip_id',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pf_amount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='salary_record',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_working_days',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.academicyear', verbose_name='Current Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main_app.classgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.section'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdocument',
            unique_together={('student', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='feeinstallment',
            unique_together={('fee_structure', 'installment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('course', 'academic_year', 'section', 'session')},
        ),
    ]
