# Generated by Django 4.2.11 on 2025-10-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_chatgroup_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='99B4DF6583B0', max_length=50, unique=True),
        ),
    ]
