# Generated by Django 4.2.11 on 2025-10-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_admissionapplication_application_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstudent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='BB0992015F20', max_length=50, unique=True),
        ),
    ]
