# Generated by Django 4.2.11 on 2025-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_notificationstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackstudent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('facility', 'Facility'), ('staff', 'Staff'), ('general', 'General'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(default='DF616BBF6BEE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
